language:
  - go 
sudo: required
services: docker
go:
  - "1.11"

script:
  - docker build . -t liupeng0518/influxdb:v1.7.5-mips64le

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push liupeng0518/influxdb:v1.7.5-mips64le
